[package]
name = "infinitystreamer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
bytes = "1.6.0"

actix-web = "4"
actix-cors = "0.7.0"
mime = "0.3.17"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"

dotenv = "0.15"
